[process_config]
point_cloud_path = "H:/Project/Scanner/src/oak/data/data-1-3.csv"
origin_data_path = "H:/Project/Scanner/src/oak/data/data_1.csv"
sensor_angle = 50.0

[render_config]
width = 800
height = 500
cam_x = -2.0
cam_y = -1.0
cam_z = -2.8